#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';
//helper
require_once __DIR__.'/core/helper.php';

use Dotenv\Dotenv;

/*
 * dotenv
 ************************/
$dotEnv = new Dotenv(__DIR__);
$dotEnv->load();

$cli = new \Symfony\Component\Console\Application('Kotori DevTools', '1.1.0');

$commands = require_once __DIR__ . '/core/DevTools/commands.php';
$classes = [];

foreach ($commands as $command)
{
    $classes[] = new $command;
}

$cli->addCommands($classes);
$cli->run();