#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use KTRLib\Config;
use Phalcon\Loader;

define('APP_BASE_PATH', realpath(__DIR__));

$di = new \Phalcon\Di\FactoryDefault();

/*
 * services
 ************************/
$serviceConf = Config::factory('services.php');
if($serviceConf->count() > 0) {
    foreach ($serviceConf as $name => $class) {
        $di->set($name, $class);
    }
}

//クロージャでの登録
require_once __DIR__.'/conf/services_from_closure.php';

/*
 * dotenv
 ************************/
$env = $di->get('env');
$env->load();

$loadConf = Config::factory('loader.php');

if (!empty($loadConf))
{
    $loader = new Loader();
    $loader->registerNamespaces($loadConf->toArray())->register();
}

(new \KTRLib\Console())->run();