#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';
//helper
require_once __DIR__.'/core/helper.php';

use Dotenv\Dotenv;
use KTR\Config;
use Phalcon\Loader;

/*
 * dotenv
 ************************/
$dotEnv = new Dotenv(__DIR__);
$dotEnv->load();

$loadConf = Config::factory('loader.php');

if (!empty($loadConf))
{
    $loader = new Loader();
    $loader->registerNamespaces($loadConf->toArray())->register();
}

$cli = new \Symfony\Component\Console\Application('Kotori DevTools', '1.1.0');

$commands = \KTR\Config::factory(__DIR__ . '/core/DevTools/commands.php')->toArray();
$userCom = \KTR\Config::factory('commands.php');
if($userCom !== false && !empty($userCom->toArray())) $commands = array_merge($commands, $userCom->toArray());

$classes = [];

foreach ($commands as $command)
{
    $classes[] = new $command;
}

$cli->addCommands($classes);
$cli->run();